---
- hosts: localhost
  connection: local
  roles:
    - role: indigo-dc.docker
      docker_bridge_ip: "172.0.17.1"

    - role: indigo-dc.consul
      consul_mode: "server"
      docker_bridge_ip: "172.0.17.1"
      consul_servers: "{{ consul_server_ips }}"

    - role: indigo-dc.zookeeper
      zookeeper_host_list: "{{ zookeeper_host_list_ips }}"

    - role: indigo-dc.mesos
      mesos_install_mode: "master"
      zookeeper_peers: "{{ zookeeper_peers_ips }}"
      mesos_masters_list: "{{ mesos_masters_list_ips }}"

    - role: indigo-dc.marathon
      zookeeper_peers: "{{ zookeeper_peers_ips }}"
      marathon_username: "{{ marathon_user }}"
      marathon_password: "{{ marathon_pass }}"

    - role: indigo-dc.cms_config
      cms_config_mysquid_host: "{{ mysquid_ip }}"
      cms_config_proxycache_host: "{{ proxycache_ip }}"
      cms_config_iamtoken: "{{ iam_token }}"
      marathon_username: "{{ marathon_user }}"
      marathon_password: "{{ marathon_pass }}"

