##################################
##           HANDLERS           ##
##################################
- handlers:
  - name: restart dnsmasq
    service: name=dnsmasq state=restarted
  - name: restart networking
    shell: ifup eth0:0
    when: virtual_interface.changed

##################################
##           VARIABLES          ##
##################################
  vars:
    ##############################
    #      CONSUL VARIABLES      #
    ##############################
    consul_advertise: "{{ansible_default_ipv4.address}}"
    consul_join_ip: "{{ mesos_master_ips[0] }}"
    consul_version: 'latest'
    consul_image: "progrium/consul:{{consul_version}}"
    ##############################
    #      DNSMASK VARIABLES     #
    ##############################
    consul_domain: consul
    ##############################
    #      HAPROXY VARIABLES     #
    ##############################
    haproxy_consul_mode: "marathon"
    haproxy_consul_version: 'latest'
    haproxy_consul_image: "ciscocloud/haproxy-consul:{{haproxy_consul_version}}"
    ##############################
    #    KEEPALIVED VARIABLES    #
    ##############################
    keepalived_virtual_ip: "{{keepalived_vip[0]}}"
    first_load_balancer_ip: "{{load_balancer_ips[0]}}"
    keepalived_role: "slave"
    keepalived_version: 'latest'
    keepalived_image: "indigodatacloud/keepalived:{{keepalived_version}}"
    keepalived_priority: "100"

##################################
##            TASKS             ##
##################################
  tasks:
  - name: Configure Slave Load Balancer
    debug: msg="Configure Slave Load Balancer"
    ##############################
    #         START CONSUL       #
    ##############################
    # INFO
  - name: Consul variables
    debug: msg="Consul image --> {{consul_image}}"
  - name: Consul variables
    debug: msg="Docker bridge IP --> {{docker_bridge_ip}}"
  - name: Consul variables
    debug: msg="Hostname --> {{ansible_hostname}}"
  - name: Consul variables
    debug: msg="Consul advertise --> {{consul_advertise}}"
  - name: Consul variables
    debug: msg="Consul join ip --> {{consul_join_ip}}"
    # RUN CONTAINER
  - name: run consul client container with join ip
    docker:
      name: consul
      image: "{{ consul_image }}"
      state: started
      detach: true
      restart_policy: always
      net: "bridge"
      ports:
       - 8300:8300
       - 8301:8301
       - 8301:8301/udp
       - 8302:8302
       - 8302:8302/udp
       - 8400:8400
       - 8500:8500
       - "{{ docker_bridge_ip }}:8600:53"
       - "{{ docker_bridge_ip }}:8600:53/udp"
      volumes:
      - /mnt:/data
      hostname: "{{ ansible_hostname }}"
      command: -advertise "{{consul_advertise}}" -join "{{consul_join_ip}}" -ui-dir /ui

  ##############################
  #      CONFIGURE DNSMASK     #
  ##############################
    # INFO
  - name: DNSMask variables
    debug: msg="Consul domain --> {{consul_domain}}"
  - name: DNSMask variables
    debug: msg="Docker bridge IP --> {{docker_bridge_ip}}"
    # CONFIG
  - name: configure consul resolution dnsmasq
    copy:
      content: "server=/{{ consul_domain }}/{{ docker_bridge_ip }}#8600"
      dest: /etc/dnsmasq.d/10-consul
      owner: root
      group: root
      mode: 0644
    notify:
      - restart dnsmasq
    tags: dnsmasq

  - name: make sure dnsmasq is running
    service:
      name: dnsmasq
      state: started
      enabled: yes
    tags: dnsmasq

  - name: configure docker
    lineinfile:
      dest: /etc/default/docker
      state: present
      insertafter: ^DOCKER_OPTS=.*
      line: "DOCKER_OPTS=\"$DOCKER_OPTS --dns {{ docker_bridge_ip }} --dns 8.8.8.8 --dns-search service.{{ consul_domain }} \""
    notify:
      - restart docker
    tags: dnsmasq

  - meta: flush_handlers

  ##############################
  #    START HAPROXY-CONSUL    #
  ##############################
    # INFO
  - name: Haproxy-Consul Variables
    debug: msg="Haproxy-Consul Image --> {{haproxy_consul_image}}"
  - name: Haproxy-Consul Variables
    debug: msg="Haproxy-Consul mode --> {{haproxy_consul_mode}}"
    # RUN CONTAINER
  - name: run haproxy-consul container
    docker:
      name: haproxy
      image: "{{ haproxy_consul_image }}"
      state: started
      detach: true
      restart_policy: always
      net: "host"
      env:
        HAPROXY_MODE: "{{haproxy_consul_mode}}"
    tags: haproxy-consul

  ##############################
  #      START KEEPALIVED      #
  ##############################
    # INFO
  - name: KeepAlived Variables
    debug: msg="KeepAlived Image --> {{keepalived_image}}"
  - name: KeepAlived Variables
    debug: msg="KeepAlived Priority --> {{keepalived_priority}}"
  - name: KeepAlived Variables
    debug: msg="KeepAlived Virtual IP --> {{keepalived_virtual_ip}}"
    # RUN CONTAINER
  - name: run keepalived container
    docker:
      name: keepalived
      image: "{{ keepalived_image }}"
      state: started
      detach: true
      restart_policy: always
      net: "host"
      privileged: true
      env:
        KEEPALIVED_PRIORITY: "{{ keepalived_priority }}"
        KEEPALIVED_VIRTUAL_IP: "{{ keepalived_virtual_ip }}"
    tags: keepalived
