---
- hosts: localhost
  connection: local
  vars:
    docker_bridge_ip: "172.0.17.1"
  pre_tasks:
    - set_fact: 
        marathon_lb_marathon_url: "https://{{ master_ips[0]  }}:8443"
        marathon_lb_service_discovery: "none" 
      when: (enable_consul_sd == false)
  roles:
    - role: indigo-dc.docker

    - role: indigo-dc.consul
      consul_mode: "agent"
      consul_servers: "{{ master_ips }}"
      when: (enable_consul_sd == true)

    - role: indigo-dc.marathon-lb
      marathon_lb_auth_creds: "{{marathon_username}}:{{marathon_password}}"
