---
- hosts: localhost
  tasks:
  - name: "get TFaaS template"
    get_url:
      url: https://raw.githubusercontent.com/indigo-dc/tosca-types/dciangot/artifacts/TFaaS/TFaaS_deploy.j2
      dest: /etc/TFaaS_deploy.j2
  - name: "Compile config template TFaaS"
    template:
      src: /etc/TFaaS_deploy.j2
      dest: /etc/TFaaS_deploy.yml
  - name: "Deploy TFaaS"
    command: kubectl create -f /etc/TFaaS_deploy.yml
