---
- hosts: localhost
  connection: local
  vars:
    SUBNET: "{{ hostvars[groups['ophidia_io'][0]]['ansible_default_ipv4']['network'] }}/{{ hostvars[groups['ophidia_io'][0]]['ansible_default_ipv4']['netmask'] }}"
  roles:
    - role: indigo-dc.ophidia-cluster
      node_type: 'server'
      deploy_type: 'install'
    - role: indigo-dc.ophidia-cluster
      node_type: 'server'
      deploy_type: 'configure'
      slurm_nodes_ips: "{{ groups['ophidia_io']|map('extract', hostvars, 'ansible_default_ipv4')|list }}"
      mysql_subnet: "{{ SUBNET }}"
      compute_subnet: "{{ SUBNET }}"
      slurm_nodes_name: vnode-
