---
 - vars:
      PBS_SERVER_CONF: |
        create queue batch
        set queue batch queue_type = Execution
        set queue batch resources_default.nodes = 1
        set queue batch enabled = True
        set queue batch started = True
        set server default_queue = batch
        set server scheduling = True
        set server scheduler_iteration = 20
        set server node_check_rate = 40
        set server resources_default.neednodes = 1
        set server resources_default.nodect = 1
        set server resources_default.nodes = 1
        set server query_other_jobs = True
        set server node_pack = False
        set server job_stat_rate = 30
        set server mom_job_sync = True
        set server poll_jobs = True
        set tcp_timeout = 600

   tasks:
    - set_fact: TORQUE_PATH="/var/spool/torque"
      when: ansible_os_family == "Debian"
    - set_fact: TORQUE_PATH="/var/lib/torque"
      when: ansible_os_family == "RedHat"
    
    # /etc/hosts configuration
    - lineinfile: dest=/etc/hosts regexp='torqueserver' line='{{IM_NODE_NET_1_IP}} torqueserver'
      when: IM_NODE_NET_1_IP is defined

    - lineinfile: dest=/etc/hosts regexp='torqueserver' line='{{ansible_default_ipv4.address}} torqueserver'
      when: IM_NODE_NET_1_IP is undefined
    
    - command: hostname torqueserver
    - copy: dest=/etc/torque/server_name content=torqueserver
      
    - service: name=torque-server state=started pattern=/usr/sbin/pbs_server
      when: ansible_os_family == "Debian"
    - service: name=pbs_server state=started pattern=/usr/sbin/pbs_server
      when: ansible_os_family == "RedHat"
      
    - shell: echo "{{PBS_SERVER_CONF}}" | qmgr creates={{TORQUE_PATH}}/server_priv/queues/batch
