---
- hosts: localhost
  connection: local
  pre_tasks:
  - name: "Add master mapping in hosts file"
    lineinfile: dest=/etc/hosts regexp='.*{{ slurm_front_end_ip }}.*$' line="{{ slurm_front_end_ip }} slurmserver slurmserver.localdomain" state=present
  roles:
  - role: indigo-dc.openvpn
    openvpn_type_of_node: 'wn'
    openvpn_frontname: 'slurmserver'
    when: wn_hybrid_cluster
  - role: indigo-dc.nfs
    nfs_mode: 'client'
    nfs_client_imports: [{ local: "/home", remote: "/home", server_host: "10.8.0.1" }]
    when: wn_hybrid_cluster
  - role: indigo-dc.nfs
    nfs_mode: 'client'
    nfs_client_imports: [{ local: "/home", remote: "/home", server_host: "{{ slurm_front_end_ip }}" }]
    when: not wn_hybrid_cluster
  - role: indigo-dc.slurm
    slurm_type_of_node: 'wn'
    slurm_server_ip: '{{ slurm_front_end_ip }}'