- tasks: 
    - lineinfile: dest=/etc/zabbix/zabbix_agentd.conf regexp="{{ item.var }}=" line="{{ item.var }}={{ item.value }}"
      with_items:
        - { var: "Server", value: "{{zabbix_server}}"}
        - { var: "ServerActive", value: "{{zabbix_server}}"}
        - { var: "Hostname", value: "{{ansible_hostname}}"}
        - { var: "HostMetadataItem", value: "system.uname"}
      notify: restart zabbix-agent

  handlers:
    - name: restart zabbix-agent
      service: name=zabbix-agent state=started