---
- hosts: localhost
  connection: local
  tasks:
    # General task
    - name: create epel.repo
      template: src=utils/templates/epel.repo dest=/etc/yum.repos.d/epel.repo
      when: ansible_os_family == "RedHat"
      
    # CLUES2 requirements
    - name: Apt install CLUES2 requirements in Deb system
      apt: pkg=python-sqlite,unzip
      when: ansible_os_family == "Debian"

    - name: Yum install CLUES2 requirements in REL system
      yum: pkg=python-sqlite2,unzip
      when: ansible_os_family == "RedHat"

    - name: Install CLUES pip requirements
      pip: name={{item}}
      with_items:
      - web.py
      - ply
      
    - get_url: url=https://github.com/grycap/{{item}}/archive/master.zip dest=/tmp/{{item}}.zip
      register: result
      until: result|success
      retries: 5
      delay: 1
      with_items:
      - clues
      - cpyutils

    # CLUES2 installation
    - unarchive: src=/tmp/{{item}}.zip dest=/tmp copy=no creates=/tmp/{{item}}-master
      with_items:
      - clues
      - cpyutils

    # CLUES2 INDIGO Orchestrator plugin      
    - get_url: url=https://raw.githubusercontent.com/indigo-dc/clues-indigo/master/indigo_orchestrator.py dest=/tmp/clues-master/cluesplugins/indigo_orchestrator.py
      register: result
      until: result|success
      retries: 5
      delay: 1

    - command: pip install -e /tmp/cpyutils-master
    - command: pip install -e /tmp/clues-master

    # This only works with ansible 2.X
    #- pip: name='/tmp/cpyutils-master' editable=true
    #- pip: name='/tmp/clues-master' editable=true