---
- hosts: localhost
  connection: local
  tasks:
    - name: Jupyterhub-kubespawner container
      docker_container:
        name: jupyterhub
        image: grycap/jupyterhub-kubespawner
        state: started
        volumes:
        - "/etc/kubernetes/admin.conf:/root/.kube/config"
        exposed_ports:
          - 8000
          - 8081
        ports:
        - "8000:8000"
        - "8081:8081"
        env:
          HUB_CONNECT_IP: "{{ ansible_default_ipv4.address }}"
